"""Add avatar_url and make password nullable

Revision ID: b00100100100
Revises: a32f40d3601a
Create Date: 2026-10-05 19:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b00100100100"
down_revision: Union[str, None] = "a32f40d3601a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
