name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/getbalanceai_api
            
            # Обновляем код
            git pull origin main
            
            # Пересобираем и запускаем контейнеры в фоне
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
            
            # Очищаем старые неиспользуемые образы Docker для экономии места
            docker image prune -f
